version: '3.8'
services:
  postgres-e-commerce_platform:
    container_name: e-commerce_platform
    image: postgres:latest
    environment:
      POSTGRES_DB: e-commerce_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped