spring:
  application:
    name: e-commerce_platform
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce_platform
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /v3/swagger-ui.html

application:
  security:
    jwt:
      secret-key: cyKiCWf0E+gMexgr+jM/DHBYrxiDVsey4UzMVTS2dWVmouQVBNFcHnrhaeNnHvNK
      expiration: 2592000000
      refresh-token:
        expiration: 2592000000

paypal:
  mode: sandbox
  clientId: ${client}
  secret: ${secret}